apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: robdw6y89-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:68de49cbd7262580c4821db8e4133ef8afd26f25@sha256:e41bf10a5d0e0e1d159c265f324fb5787f19811cfd7b33632c0f0f674236fb14
          name: container-image
